# Generated by Django 6.0.3 on 2026-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids'), ('ACCESSORIES', 'Accessories'), ('SHOES', 'Shoes'), ('SPORTS', 'Sportswear')], max_length=20)),
                ('image', models.ImageField(upload_to='garments/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
