# Generated by Django 6.0.3 on 2026-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_garment_available_colors_garment_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='available_colors',
            field=models.CharField(blank=True, default='olive,blue,red,black', help_text='Comma-separated colors (names or HEX like #556B2F)', max_length=255),
        ),
        migrations.AlterField(
            model_name='garment',
            name='available_sizes',
            field=models.CharField(blank=True, default='S,M,L,XL', help_text='Comma-separated sizes e.g. S,M,L,XL', max_length=100),
        ),
        migrations.AlterField(
            model_name='garment',
            name='fabric_type',
            field=models.CharField(blank=True, default='Premium Cotton', help_text='e.g. Linen, Silk, Cotton', max_length=100),
        ),
    ]
