# Generated by Django 6.0.3 on 2026-03-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_garment_available_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='garment',
            name='available_sizes',
            field=models.CharField(default='S,M,L,XL', max_length=100),
        ),
        migrations.AlterField(
            model_name='garment',
            name='fabric_type',
            field=models.CharField(default='Premium Cotton', max_length=100),
        ),
        migrations.CreateModel(
            name='GarmentVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(max_length=7)),
                ('variant_image', models.ImageField(upload_to='garments/variants/')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.garment')),
            ],
        ),
    ]
