# Generated by Django 6.0.3 on 2026-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_garment_available_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='finishing_method',
            field=models.CharField(choices=[('READY-MADE', 'Ready-Made'), ('BESPOKE', 'Bespoke')], default='READY-MADE', max_length=20),
        ),
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(choices=[('SHIRT', 'Shirt'), ('TROUSER', 'Trouser'), ('SUIT', 'Suit'), ('BLAZER', 'Blazer'), ('TSHIRT', 'Tshirt')], max_length=20),
        ),
    ]
