# Generated by Django 6.0.3 on 2026-03-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_garment_finishing_method_alter_garment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('FABRIC', 'Fabric Swatch'), ('COLLAR', 'Collar Style'), ('BUTTON', 'Button Type'), ('SLEEVE', 'Sleeve Style'), ('CUFF', 'Cuff Style')], max_length=20)),
                ('image', models.ImageField(upload_to='bespoke/components/')),
                ('target_category', models.CharField(choices=[('SHIRT', 'Shirt'), ('TROUSER', 'Trouser'), ('SUIT', 'Suit'), ('BLAZER', 'Blazer'), ('TSHIRT', 'Tshirt')], max_length=20)),
            ],
        ),
    ]
