# Generated by Django 6.0.3 on 2026-03-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bespokecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeGarment',
            fields=[
            ],
            options={
                'verbose_name': 'Bespoke Fabric',
                'verbose_name_plural': '02. Bespoke Fabrics',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.garment',),
        ),
        migrations.CreateModel(
            name='ReadyMadeGarment',
            fields=[
            ],
            options={
                'verbose_name': 'Ready-Made Item',
                'verbose_name_plural': '01. Ready-Made Collection',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.garment',),
        ),
    ]
