# Generated by Django 6.0.3 on 2026-03-16 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bespokegarment_readymadegarment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attr_type', models.CharField(choices=[('FABRIC', 'Fabric Swatch'), ('COLLAR', 'Collar Style'), ('BUTTON', 'Button Type'), ('CUFF', 'Cuff Style'), ('SLEEVE', 'Sleeve Style')], max_length=20)),
                ('color_hex', models.CharField(blank=True, help_text='e.g. #0000FF for blue', max_length=7, null=True)),
                ('image', models.ImageField(upload_to='bespoke/attributes/')),
            ],
        ),
        migrations.DeleteModel(
            name='BespokeComponent',
        ),
        migrations.AlterModelOptions(
            name='bespokegarment',
            options={'verbose_name': 'Bespoke Result Shirt', 'verbose_name_plural': '02. Bespoke Result Shirts'},
        ),
        migrations.RemoveField(
            model_name='garment',
            name='fabric_type',
        ),
        migrations.AddField(
            model_name='garment',
            name='fabric_type_label',
            field=models.CharField(default='Premium Selection', max_length=100),
        ),
        migrations.CreateModel(
            name='BespokePalette',
            fields=[
            ],
            options={
                'verbose_name': 'Bespoke Attribute',
                'verbose_name_plural': '03. Bespoke Attributes (Fabrics/Features)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.bespokeattribute',),
        ),
        migrations.AddField(
            model_name='garment',
            name='button_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garment_button', to='catalog.bespokeattribute'),
        ),
        migrations.AddField(
            model_name='garment',
            name='collar_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garment_collar', to='catalog.bespokeattribute'),
        ),
        migrations.AddField(
            model_name='garment',
            name='cuff_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garment_cuff', to='catalog.bespokeattribute'),
        ),
        migrations.AddField(
            model_name='garment',
            name='fabric_attr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garment_fabric', to='catalog.bespokeattribute'),
        ),
    ]
