# Generated by Django 6.0.3 on 2026-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bespokeattribute_delete_bespokecomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='gender',
            field=models.CharField(blank=True, choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('KIDS', 'Kids')], max_length=10, null=True),
        ),
    ]
